apiVersion: v1
kind: Service
metadata:
  name: {{ include "tidalwave.fullname" . }}-backend
  labels:
    {{- include "tidalwave.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tidalwave.backendSelectorLabels" . | nindent 4 }}
