{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tidalwave.fullname" . }}
  labels:
    {{- include "tidalwave.labels" . | nindent 4 }}
type: Opaque
stringData:
  TIDALWAVE_DATABASE_URL: {{ required "secrets.databaseUrl is required" .Values.secrets.databaseUrl | quote }}
  TIDALWAVE_LASTFM_API_KEY: {{ .Values.secrets.lastfmApiKey | quote }}
  TIDALWAVE_LASTFM_API_SECRET: {{ .Values.secrets.lastfmApiSecret | quote }}
  TIDALWAVE_SESSION_SECRET: {{ required "secrets.sessionSecret is required" .Values.secrets.sessionSecret | quote }}
{{- end }}
