"""baseline schema

Revision ID: c01b5b802766
Revises: 
Create Date: 2026-06-17 14:11:25.896627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01b5b802766'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastfm_username', sa.String(length=255), nullable=False),
    sa.Column('lastfm_session_key', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('disconnected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lastfm_username')
    )
    op.create_table('listens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_title', sa.Text(), nullable=False),
    sa.Column('artist', sa.Text(), nullable=False),
    sa.Column('album', sa.Text(), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('track_mbid', sa.String(length=36), nullable=True),
    sa.Column('artist_mbid', sa.String(length=36), nullable=True),
    sa.Column('album_mbid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'artist', 'track_title', 'played_at', name='uq_listen_dedup')
    )
    op.create_index(op.f('ix_listens_played_at'), 'listens', ['played_at'], unique=False)
    op.create_index(op.f('ix_listens_user_id'), 'listens', ['user_id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('share_token', sa.String(length=43), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('range_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('range_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_shares_user_id'), 'shares', ['user_id'], unique=False)
    op.create_table('sync_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_shares_user_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_listens_user_id'), table_name='listens')
    op.drop_index(op.f('ix_listens_played_at'), table_name='listens')
    op.drop_table('listens')
    op.drop_table('users')
    # ### end Alembic commands ###
